# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-22 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailganer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailslog',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
