# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-22 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailganer', '0002_emailslog_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailslog',
            name='reject_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
